### ISSUE TITLE
Restore previous clipboard after pasting

### ISSUE THREAD

**Issue by ChildishGiant** [cassidyjames/ideogram#63] opened 2021-12-19 21:31 UTC
Currently the existing clipboard is replaced, it'd be nice if the clipboard was read, stored and restored once the emoji is pasted. If the user wants to have multiple of the same emoji in a row (Which I don't think is wanted often) they can copy the one that's already pasted

**Comment by cassidyjames** [comment] 2021-12-21 20:12
Agreed, but this is a duplicate of #17 :smile:

**Closed as completed by cassidyjames** 2021-12-21 20:12 UTC
Labels: duplicate
