### ISSUE TITLE
Suggestion: Can you please make this app elementary os 6 compatible

### ISSUE THREAD

**Issue by danik4985** [cassidyjames/ideogram#61] opened 2021-09-18 07:23 UTC
According to appcenter, this app can only be used on elementary os 5.1. I'm sure that I am not the only one who would like to use this app on elementary os 6. Can you please make it eos6 compatible? Thanks!

**Comment by cassidyjames** [comment] 2021-09-20 19:32
Thanks for opening this! However, it's a duplicate of #4. Work is being done at #57.

**Closed by cassidyjames** 2021-09-20 19:32 UTC
